Add dark mode
sogrim/technion-sogrim pull request #182
Opened 2023-01-16 19:45 UTC by benny-n

2023-02-04 10:08 UTC, liadaram1 requested changes

2023-02-04 10:08 UTC, liadaram1 commented on packages/sogrim-app/src/components/App/UserApp.tsx
> +      }
I think there might be a bug here.
What will happen in the following scenario:
The user changes in his device to dark mode. Now the value of `data.settings.dark_mode` is `true`.
Next, he is connecting from a different device, and changes back to `light mode`.
IMHO there will be a limbo state, where his original device will still be dark mode and his second device light mode.

2023-02-04 10:28 UTC, liadaram1 requested changes

2023-02-04 10:28 UTC, liadaram1 commented on packages/server/src/resources/user.rs
>  #[derive(Default, Clone, Debug, Deserialize, Serialize)]
In addition, I tried to use the `dark_mode` locally, and there is an annoying state where after changing the mode, and refresh the page we get the pop up "סטטוס התואר שלך לא מעודכן...".

2023-02-04 10:34 UTC, liadaram1 commented on packages/sogrim-app/src/components/App/UserApp.tsx
> +      }
Ok I found a way to test it locally and it seems I am wrong :).
Closing the comment.

2023-02-04 12:42 UTC, benny-n commented
This (breaking) change requires us to run 3 queries on the next release:
1. Update dark mode option: 
```js
db.Users.update({}, {$set: {"settings.dark_mode": true}})
```
2. Remove `compute_in_progress` from `UserSettings`: 
```js
db.Users.update({}, {$unset: {"settings.compute_in_progress": ""}})
```
3. Add `compute_in_progress` to `UserDetails`: 
```js
db.Users.update({}, {$set: {"settings.compute_in_progress": false}})
```

2023-02-07 18:56 UTC, liadaram1 approved these changes

2023-02-07 18:56 UTC, merged